### ISSUE TITLE
Unable to install cask `logitech-options`

### ISSUE THREAD

**Issue by JigSawFr** [caskroom/homebrew-drivers#137]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Unable to install cask `logitech-options`

#### Output of your command with `--verbose --debug`

```
jigsaw@macbook-pro-2  ~  brew cask install logitech-options --verbose --debug                                                                                                       130 ↵  1149  19:47:18 
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
You must reboot for the installation of logitech-options to take effect.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.logitech.com/pub/techsupport/options/Options_6.70.938.zip
Already downloaded: /Users/jigsaw/Library/Caches/Homebrew/Cask/logitech-options--6.70.938.zip
==> Downloaded to -> /Users/jigsaw/Library/Caches/Homebrew/Cask/logitech-options--6.70.938.zip
==> Verifying download
==> Determining which verifications to run for Cask logitech-options
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask logitech-options
==> SHA256 checksums match
==> Installing Cask logitech-options
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/jigsaw/Library/Caches/Homebrew/Cask/logitech-options--6.70.938.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/jigsaw/Library/Caches/Homebrew/Cask/logitech-options--6.70.938.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/jigsaw/Library/Caches/Homebrew/Cask/logitech-options--6.70.938.zip", "/var/folders/1d/9fbp7fs90bsdbxryvvkk1cn00000gn/T/d20170901-49642-1mgiwis"]
==> Creating metadata directory /usr/local/Caskroom/logitech-options/.metadata/6.70.938/20170901174724.884.
==> Creating metadata subdirectory /usr/local/Caskroom/logitech-options/.metadata/6.70.938/20170901174724.884/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask logitech-options
==> 2 artifact/s defined
#<Hbc::Artifact::Uninstall:0x007fdc5914b8f0>
#<Hbc::Artifact::Pkg:0x007fdc5914b7b0>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for logitech-options; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Purging files for version 6.70.938 of Cask logitech-options
Error: pkg source file not found: '/usr/local/Caskroom/logitech-options/6.70.938/LogiMgr Installer 6.70.938.app/Contents/Resources/LogiMgr.mpkg'
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

```
 jigsaw@macbook-pro-2  ~  brew cask doctor                                                                                                                                             1 ↵  1150  19:47:24 
==> Homebrew-Cask Version
Homebrew-Cask 1.3.1-150-g8187776
caskroom/homebrew-cask (git revision 7b6ab; last commit 2017-09-01)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (4 files, 202MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3718 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (113 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (165 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="fr_FR.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

Thank you :)

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-drivers/pull/139
