### ISSUE TITLE
checksum mismatch for logitech-options

### ISSUE THREAD

**Issue by daften** [caskroom/homebrew-drivers#149]
#### General troubleshooting steps

- [ X] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [ X] None of the templates was appropriate for my issue, or I’m not sure.
- [ X] I ran `brew update-reset && brew update` and retried my command.
- [ X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When installing logitech-options, I get the output below, with a checksum mismatch

#### Output of your command with `--verbose --debug`

```
➜  ~ brew cask install logitech-options --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
You must reboot for the installation of logitech-options to take effect.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.logitech.com/pub/techsupport/options/Options_6.70.938.zip
/usr/bin/curl --show-error --user-agent Homebrew/1.3.2-25-g914378c (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/daften/Library/Caches/Homebrew/Cask/logitech-options--6.70.938,6.70.928.zip.incomplete https://www.logitech.com/pub/techsupport/options/Options_6.70.938.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   267  100   267    0     0    747      0 --:--:-- --:--:-- --:--:--   745
100   183  100   183    0     0    395      0 --:--:-- --:--:-- --:--:--   395
100 48.7M  100 48.7M    0     0  8880k      0  0:00:05  0:00:05 --:--:--  9.9M
==> Downloaded to -> /Users/daften/Library/Caches/Homebrew/Cask/logitech-options--6.70.938,6.70.928.zip
==> Verifying download
==> Determining which verifications to run for Cask logitech-options
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask logitech-options
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'logitech-options' does not match.

Expected: e33b78cdf5ca8030732e055d8cbe8e449682761fef4f6428636e8679efaa4e6d
Actual:   5bf0ac88897e4e521450b7c3f55275b6c85d5a4ced123e18968e8b196fe74a2f
File:     /Users/daften/Library/Caches/Homebrew/Cask/logitech-options--6.70.938,6.70.928.zip

To retry an incomplete download, remove the file above.
Error: Install incomplete.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

#### Output of `brew cask doctor`

Irrelevant, but still

```
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /opt/chefdk/embedded/bin/curl-config
  /opt/chefdk/embedded/bin/ncurses5-config
  /opt/chefdk/embedded/bin/ncursesw5-config
  /opt/chefdk/embedded/bin/pcre-config
  /opt/chefdk/embedded/bin/pkg-config
  /opt/chefdk/embedded/bin/xml2-config
  /opt/chefdk/embedded/bin/xslt-config
  /Applications/MAMP/Library/bin/curl-config
  /Applications/MAMP/Library/bin/freetype-config
  /Applications/MAMP/Library/bin/icu-config
  /Applications/MAMP/Library/bin/libmcrypt-config
  /Applications/MAMP/Library/bin/libpng-config
  /Applications/MAMP/Library/bin/libpng16-config
  /Applications/MAMP/Library/bin/Magick++-config
  /Applications/MAMP/Library/bin/Magick-config
  /Applications/MAMP/Library/bin/MagickCore-config
  /Applications/MAMP/Library/bin/MagickWand-config
  /Applications/MAMP/Library/bin/pcre-config
  /Applications/MAMP/Library/bin/pcre2-config
  /Applications/MAMP/Library/bin/pkg-config
  /Applications/MAMP/Library/bin/python-config
  /Applications/MAMP/Library/bin/python2-config
  /Applications/MAMP/Library/bin/python2.7-config
  /Applications/MAMP/Library/bin/sablot-config
  /Applications/MAMP/Library/bin/Wand-config
  /Applications/MAMP/Library/bin/x86_64-apple-darwin13.4.0-pkg-config
  /Applications/MAMP/Library/bin/xml2-config
  /Applications/MAMP/Library/bin/xslt-config
  /Applications/MAMP/Library/bin/yaz-config
  /Applications/MAMP/bin/php/php7.1.6/bin/php-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libbeid.2.7.4.dylib
  /usr/local/lib/libbeidcardlayer.4.0.7.dylib
  /usr/local/lib/libbeidcommon.1.0.0.dylib
  /usr/local/lib/libbeidcommon.4.0.7.dylib
  /usr/local/lib/libbeiddialogsQT.4.0.7.dylib
  /usr/local/lib/libbeidgui.1.5.0.dylib
  /usr/local/lib/libbeidlibjni.2.7.2.dylib
  /usr/local/lib/libbeidlibopensc.2.2.0.dylib
  /usr/local/lib/libbeidlibopenscinternal.2.2.0.dylib
  /usr/local/lib/libbeidpkcs11.4.0.7.dylib
  /usr/local/lib/libbeidpkcs11.4.1.11.dylib
  /usr/local/lib/libbeidpkcs11.4.1.19.dylib
  /usr/local/lib/libbeidpkcs11.4.1.8.dylib
  /usr/local/lib/libqt-mt.3.3.8.dylib
  /usr/local/lib/libxerces-c-3.1.dylib

Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /opt/chefdk/embedded/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/etc/bash_completion.d/brew_bash_completion.sh
  /usr/local/lib/libbeidapplayer.4.0.dylib
  /usr/local/lib/libbeidapplayer.4.dylib
  /usr/local/lib/libbeidapplayer.dylib
  /usr/local/lib/libbeidlib.4.0.dylib
  /usr/local/lib/libbeidlib.4.dylib
  /usr/local/lib/libbeidlib.dylib
  /usr/local/lib/libbeidlibJava_Wrapper.4.0.dylib
  /usr/local/lib/libbeidlibJava_Wrapper.4.dylib
  /usr/local/lib/libbeidlibJava_Wrapper.dylib
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-drivers/pull/150
